job_id: eve_spectformer
data:
  sdo_data_root_path: /nobackupnfs1/sroy14/processed_data/Helio/nc
  train_data_path: ./assets/train_index_surya_1_0.csv
  valid_data_path: ./assets/valid_index_surya_1_0.csv
  train_solar_data_path : ./assets/euv-spectra/archive/AIA_EVE_temporally_stratified.nc
  valid_solar_data_path : ./assets/euv-spectra/archive/AIA_EVE_temporally_stratified.nc
  channels: ['aia94', 'aia131', 'aia171', 'aia193', 'aia211', 'aia304', 'aia335', 'aia1600', 'hmi_m', 'hmi_bx', 'hmi_by', 'hmi_bz', 'hmi_v']
  time_delta_input_minutes: [0]
  time_delta_target_minutes: +60
  # n_input_timestamps: 1 #Optional integer to randomly sample time_delta_input_minutes
  batch_size: 1
  num_data_workers: 4
  prefetch_factor: 2
  pooling: 1
  random_vert_flip: false
  scalers_path: ./assets/scalers.yaml

model:
  model_type: spectformer # Options: spectformer, resnet18, resnet34, resnet50, alexnet, mobilenet
  # Spectformer options
  img_size: 4096
  patch_size: 16
  in_channels: 13
  time_embedding:
    type: linear      # Options: linear, fourier, perceiver
    n_queries: null   # Integer for perceiver; otherwise null
    time_dim: 1       # Integer for linear and fourier; otherwise null
  embed_dim: 1280
  depth: 10
  spectral_blocks: 2
  num_heads: 16
  mlp_ratio: 4.0
  rpe: false
  drop_rate: 0.0
  window_size: 2
  dp_rank: 4
  learned_flow: false
  epochs_to_learn_flow: 0 # Start by training flow model only before freezing
  init_weights: false
  checkpoint_layers: []
  ensemble: null
  finetune: True
  nglo: 1
  global_average_pooling: False
  global_max_pooling: False
  attention_pooling: False
  transformer_pooling: False
  global_class_token: True
  penultimate_linear_layer: True
  freeze_backbone: True
  dropout: 0.2

optimizer:
  warm_up_steps: 0 #2000
  max_epochs: 20
  learning_rate: 0.0001
  min_lr: 0.00001
use_latitude_in_learned_flow: false
pretrained_path: ./assets/surya.366m.v1.pt

num_mask_aia_channels: 0
drop_hmi_probablity: 0.0
validate_after_epoch: 1
wandb_log_train_after: 10 # This should be less than iters_per_epoch_train
wandb_project: "helio-fm" # Typical choices: "helio-fm", "spectformer_with_metrics"
visualization_samples: 3
rollout_steps: 0
save_wt_after_iter: 1000
path_experiment: checkpoints
iters_per_epoch_train: 2000
iters_per_epoch_valid: 200
iters_grad_accum: 1
dtype: float32
parallelism: "ddp" # Valid options: "ddp" and "fsdp"
